trigger:
- main

pool:
  name: local_agent

parameters:
- name: ENV
  displayName: Select Environment
  type: string
  default: QA
  values:
  - QA
  - UAT

- name: BROWSER
  displayName: Select Browser
  type: string
  default: chrome
  values:
  - chrome
  - firefox

variables:
  ALLURE_RESULTS: target/allure-results

stages:

# ================= CHECKOUT =================
- stage: Checkout
  displayName: Checkout Code
  jobs:
  - job: CheckoutJob
    steps:
    - checkout: self

# ================= TEST =================
- stage: Test
  displayName: Clean & Execute Tests
  dependsOn: Checkout
  jobs:
  - job: RunTests
    steps:
    - script: |
        echo "Maven details"
        which mvn
        mvn -version

        mvn clean test \
          -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml \
          -Denv=${{ parameters.ENV }} \
          -Dbrowser=${{ parameters.BROWSER }}
      displayName: Maven Clean Test

    - task: PublishTestResults@2
      condition: always()
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: '**/surefire-reports/TEST-*.xml'

# ================= ALLURE =================
- stage: Allure
  displayName: Generate & Publish Allure Report
  dependsOn: Test
  jobs:
  - job: AllureReport
    steps:
    - script: |
        mvn allure:report
      displayName: Generate Allure Report

    - script: |
        if [ -d "target/allure-results" ]; then
          echo "##vso[task.setvariable variable=ALLURE_EXISTS]true"
        else
          echo "##vso[task.setvariable variable=ALLURE_EXISTS]false"
        fi
      displayName: Check Allure Results

    - task: PublishPipelineArtifact@1
      condition: eq(variables.ALLURE_EXISTS, 'true')
      inputs:
        targetPath: target/allure-results
        artifact: allure-results