trigger:
  - main

# ================= AGENT =================
pool:
  name: local_agent

# ================= PARAMETERS =================
parameters:
- name: ENV
  displayName: Select Environment
  type: string
  default: QA
  values:
    - QA
    - UAT

- name: BROWSER
  displayName: Select Browser
  type: string
  default: chrome
  values:
    - chrome
    - firefox

# ================= VARIABLES =================
variables:
  ALLURE_RESULTS: target/allure-results
  EXTENT_REPORT: test-output

# ================= STAGES =================

# ---------- CHECKOUT ----------
- stage: Checkout
  displayName: Checkout Code
  jobs:
  - job: CheckoutJob
    steps:
    - checkout: self

# ---------- BUILD & TEST ----------
- stage: Test
  displayName: Clean & Execute Tests
  dependsOn: Checkout
  jobs:
  - job: RunTests
    displayName: Run Maven Tests
    steps:
    - script: |
        echo "Using Maven:"
        which mvn
        mvn -version

        mvn clean test \
          -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml \
          -Denv=${{ parameters.ENV }} \
          -Dbrowser=${{ parameters.BROWSER }}
      displayName: Maven Clean Test

    - task: PublishTestResults@2
      displayName: Publish TestNG Results
      condition: always()
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        failTaskOnFailedTests: true

# ---------- ALLURE REPORT ----------
- stage: Allure
  displayName: Generate & Publish Allure Report
  dependsOn: Test
  jobs:
  - job: AllureReport
    steps:
    - script: |
        mvn allure:report
      displayName: Generate Allure Report

    - script: |
        if [ -d "target/allure-results" ]; then
          echo "##vso[task.setvariable variable=ALLURE_EXISTS]true"
        else
          echo "##vso[task.setvariable variable=ALLURE_EXISTS]false"
        fi
      displayName: Check Allure Results Folder

    - task: PublishPipelineArtifact@1
      displayName: Publish Allure Results
      condition: eq(variables.ALLURE_EXISTS, 'true')
      inputs:
        targetPath: target/allure-results
        artifact: allure-results

# ---------- EXTENT REPORT ----------
- stage: Extent
  displayName: Publish Extent Report
  dependsOn: Test
  jobs:
  - job: ExtentReport
    steps:
    - task: PublishPipelineArtifact@1
      displayName: Publish Extent Report
      inputs:
        targetPath: test-output
        artifact: extent-report